# Composição da biblioteca estática do arcabouço de teste

[Diretorios]

Nome        =  CriaLib
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes


[Modulos]
Carta
LISTA
TRATAMENTO_FALHA
Baralho
CELULA_TEMPORARIA
COLUNA_BASE
COLUNAS_ALEATORIAS

[Link]
    cd $(Fobj)
    LIB $(L) @$(NOME).build >> $(Ferr)\$(NOME).err

[BuildInicio]
/OUT:FreeCell.lib
/MACHINE:IX86

[Fim]
