# Composicao do programa de teste do modulo Coluna Base
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteColunaBase
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes

[Modulos]
TEST_COLUNA_BASE
COLUNA_BASE
LISTA
TRATAMENTO_FALHA
Carta

[BuildInicio]
/OUT:..\produto\TRAB2-5.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
