# Composicao do programa de teste do modulo Colunas Aleatorias
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteColunasAleatorias
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes
[Modulos]
TestCALT
COLUNAS_ALEATORIAS
Baralho
LISTA
TRATAMENTO_FALHA
Carta

[BuildInicio]
/OUT:..\produto\TRAB2-1.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
