# Composicao do programa de teste do modulo Gerenciador
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteGerenciador
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes

[Modulos]
TestGerenciador
Gerenciador
PERSISTENCIA

[BuildInicio]
/OUT:..\produto\TRAB3-2.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
FreeCell.lib
ArcaboucoTeste.lib


[Fim]
