# Composicao do programa de teste do modulo Carta
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteCarta
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes

[Modulos]
TESTCARTA
Carta

[BuildInicio]
/OUT:..\produto\TRAB2-2.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
