# Composicao do programa de teste do modulo Celula Temporaria
# Este exemplo utiliza o arcabouço completo 

[Diretorios]

Nome        =  TesteCelulasTemp
PathDefault =  ..\Fontes
err         =  ..\Produto
obj         =  ..\Objetos
c           =  ..\Fontes
h           =  ..\Fontes

[Modulos]
TESTTMP
CELULA_TEMPORARIA
LISTA
TRATAMENTO_FALHA
Carta

[BuildInicio]
/OUT:..\produto\TRAB2-3.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
