// Script:    TesteContador-Arv.script
// Autor:     Carla Galdino, Eliana Goldner e Ryniere Silva
// Data:      05/jul/2009
// Propósito: Ilustrar arquivo de script para controle de espaços dinâmicos
//

== Inicializar valores
=declararparm   lista0  int 0
=declararparm   lista1  int 1
=declararparm   lista2  int 2
=declararparm	lista3  int 3
=declararparm	lista_nula	int -10

=declararparm   str0    string  "abcdefg"
=declararparm   str1    string  "qwerty"
=declararparm   str2    string  "xxx"
=declararparm   str3    string  "xpto"

=declararparm   OK             int  0
=declararparm   ListaVazia     int  1
=declararparm   FimLista       int  2
=declararparm   NaoAchou       int  3
=declararparm	ErroEstrutura  int  4
=declararparm   FaltouMemoria  int  5
=declararparm   CondRetErro    int  6


//Modos de deturpacao 

=declararparm 	TipoCabeca 	int 1
=declararparm 	OrigemNula	int 2
=declararparm 	FimNulo		int 3
=declararparm 	CorrenteNulo	int 4
=declararparm 	OrigemLixo	int 5
=declararparm 	FimLixo	 	int 6
=declararparm 	CorrenteLixo	int 7
=declararparm 	TipoElem 	int 8
=declararparm 	PtCabecaNulo	int 9
=declararparm 	PtAntNulo	int 10
=declararparm 	PtProxNulo 	int 11
=declararparm 	PtCabecaLixo	int 12
=declararparm 	PtAntLixo	int 13
=declararparm 	PtProxLixo	int 14
=declararparm 	Valor		int 15
=declararparm 	EspacoCabeca 	int 16
=declararparm 	EspacoElem	int 17
=declararparm 	EliminaElemCorr int 18
=declararparm 	DesencadeiaElem	int 19

=declararparm   pNULL          int  0
=declararparm   pNaoNULL       int  1

== Iniciar contagem
=inicializarcontadores  "..\\Produto\\TotalizacaoContadoresTesteControleEsp"
=lercontadores          "..\\Scripts\\DeclaracaodecontadoresLista"
=zerartodoscontadores
=iniciarcontagem

== Verificar Criar a lista 0
=criarlista      lista0

== Verificar espaços alocados
=verificartodosespacos       1
=obternumeroespacosalocados  1

== Verificar Criar a lista 0
=criarlista      lista1

== Verificar espaços alocados
=verificartodosespacos       1
=obternumeroespacosalocados  2

== Verificar assertivas de entrada de avancarElem
=avancarelem      lista0  1  ListaVazia

== Verificar comando recuperar
=avancarelem      lista0   1     OK
=recuperar 

== Verificar espaços alocados
=verificartodosespacos       1
=obternumeroespacosalocados  2

== Verificar Destruir lista
=destruirlista		lista0

== Verificar espaços alocados
=verificartodosespacos       1
=obternumeroespacosalocados  1

== Verificar inserir elem antes com limite de memória
=limitarmemoriadisponivel		30
=inselemantes	lista1		str0	FaltouMemoria

== Verificar espaços alocados
=verificartodosespacos       1
=obternumeroespacosalocados  1

== Verificar inserirElementoAntes: Encadeamento de elemento em lista vazia.
=eliminarlimitesespaco
=inselemantes lista1	str1	OK

== Verificar espaços alocados + 1 elemento + 1 pValor
=verificartodosespacos       1
=obternumeroespacosalocados  3

== Verificar inserirElementoAntes: Encadeamento de elemento quando o elemento corrente é primeiro.
=inselemantes lista1	str2	OK

== Verificar espaços alocados + 1 elemento + 1 pValor
=verificartodosespacos       1
=obternumeroespacosalocados  5

== Verificar inserirElementoAntes: Encadeamento de elemento quando o elemento corrente não é o primeiro.
=avancarelem      lista1   1     OK
=inselemantes 	lista1	str3	OK

== Verificar espaços alocados + 1 elemento + 1 pValor
=verificartodosespacos       1
=obternumeroespacosalocados  7

== Verificar inserirElementoApos: Encadeamento de elemento em lista vazia.
=criarlista      lista2
=inselemapos	lista2		str1	OK

== Verificar espaços alocados + 1 pLista + 1 elemento + 1 pValor
=verificartodosespacos       1
=obternumeroespacosalocados  10

== Verificar inserirElementoApos: LIS_InserirElementoApos: Encadeamento de elemento quando o elemento corrente é o último
=inselemapos	lista2		str1	OK

== Verificar espaços alocados + 1 elemento + 1 pValor
=verificartodosespacos       1
=obternumeroespacosalocados  12


== Verificar inserirElementoApos: Encadeamento de elemento quando o elemento corrente não é o último.
=avancarelem      lista2   -1     OK
=inselemapos	lista2		str2	OK

== Verificar espaços alocados + 1 elemento + 1 pValor
=verificartodosespacos       1
=obternumeroespacosalocados  14

== Verificar IrInicioLista
=irinicio lista2

== Verificar espaços alocados + 0 espaços
=verificartodosespacos       1
=obternumeroespacosalocados  14

== Verificar Excluir Elemento: Excluir elemento em lista vazia.
=criarlista		lista3
=excluirelem	lista3   ListaVazia

== Verificar espaços alocados + 1 espaço cabeçaLista - 0 espaços excuidos
=verificartodosespacos       1
=obternumeroespacosalocados  15

== Verificar Excluir Elemento: Excluir origem lista.
=inselemantes	lista3		str3	OK

== Verificar espaços alocados + 1 espaço elemento + 1 espaço pValor
=verificartodosespacos       1
=obternumeroespacosalocados  17



=terminarcontadores  OK

// fim





