// Script:    TesteDeturpaLista.script
// Autor:     Carla Galdino, Eliana Goldner e Ryniere Silva
// Propósito: Testar o verificador da lista, deturpando sua estrutrura
//

==Declara parametros

=declararparm 	OK 		int 0
=declararparm 	ListaVazia 	int 1
=declararparm 	FimLista	int 2
=declararparm 	NaoAchou	int 3
=declararparm 	ErroEstrutura	int 4
=declararparm 	FaltouMemoria	int 5
=declararparm 	Erro		int 6

=declararparm   str0    string  "abcdefg"
=declararparm   str1    string  "qwerty"
=declararparm   str2    string  "xxx"
=declararparm   str3    string  "xpto"
=declararparm   str4    string  "xpto2"

=declararparm   FALSE          int  0
=declararparm   TRUE	       int  1

=declararparm   pNULL          int  0
=declararparm   pNaoNULL       int  1

//Modos de deturpacao 

=declararparm 	TipoCabeca 	int 1
=declararparm 	OrigemNula	int 2
=declararparm 	FimNulo		int 3
=declararparm 	CorrenteNulo	int 4
=declararparm 	OrigemLixo	int 5
=declararparm 	FimLixo	 	int 6
=declararparm 	CorrenteLixo	int 7
=declararparm 	TipoElem 	int 8
=declararparm 	PtCabecaNulo	int 9
=declararparm 	PtAntNulo	int 10
=declararparm 	PtProxNulo 	int 11
=declararparm 	PtCabecaLixo	int 12
=declararparm 	PtAntLixo	int 13
=declararparm 	PtProxLixo	int 14
=declararparm 	Valor		int 15
=declararparm 	EspacoCabeca 	int 16
=declararparm 	EspacoElem	int 17
=declararparm 	EliminaElemCorr int 18
=declararparm 	DesencadeiaElem	int 19

== Iniciar contagem
=inicializarcontadores  "."

== Determinar controle de pValores alocados para teste
=controlarvaloresalocados	TRUE

== Criar Lista
=criarlista      0
=inselemantes    0   str0  OK
=inselemapos     0   str1  OK
=inselemapos     0   str2  OK
=inselemapos     0   str3  OK
=inselemapos     0   str4  OK
=obtervalorelem  0   str4  pNaoNULL

== Verificar lista
=verificarlista   0	OK

== Deturpar tipo elemento
=deturpar        0   TipoElem
=verificarlista  0   ErroEstrutura
=AceitaFalhasAcumuladas 1

== Destruir a lista
=destruirlista   0

== Criar Lista
=criarlista      0
=inselemantes    0   str0  OK
=inselemapos     0   str1  OK
=inselemapos     0   str2  OK
=inselemapos     0   str3  OK
=inselemapos     0   str4  OK
=obtervalorelem  0   str4  pNaoNULL

== Anular ponteiro para cabeca
=deturpar        0   PtCabecaNulo
=verificarlista  0   ErroEstrutura
=AceitaFalhasAcumuladas 1

== Destruir a lista
=destruirlista   0
=obternumeroespacosalocados   0

== Criar Lista
=criarlista      0
=inselemantes    0   str0  OK
=inselemapos     0   str1  OK
=inselemapos     0   str2  OK
=inselemapos     0   str3  OK
=inselemapos     0   str4  OK
=obtervalorelem  0   str4  pNaoNULL

== Anular ponteiro para anterior
=deturpar        0   PtAntNulo
=verificarlista  0   ErroEstrutura
=AceitaFalhasAcumuladas 1

== Destruir a lista
=destruirlista   0
=verificarmemoria           // vazia
=obternumeroespacosalocados  0

== Criar Lista
=criarlista      0
=inselemantes    0   str0  OK
=inselemapos     0   str1  OK
=inselemapos     0   str2  OK
=inselemapos     0   str3  OK
=inselemapos     0   str4  OK
=obtervalorelem  0   str4  pNaoNULL
=avancarelem	 0   -1    OK      //Corrente no ultimo elemento, que tem proximo nulo - Posiciona corrente no meio

== Anular ponteiro para proximo
=deturpar          0   PtProxNulo
=verificarlista    0   ErroEstrutura 
=AceitaFalhasAcumuladas 1  

== Destruir a lista
=destruirlista     0        // sobra 1
=verificarmemoria
=obternumeroespacosalocados  1

== Criar Lista
=criarlista      0
=inselemantes    0   str0  OK
=inselemapos     0   str1  OK
=inselemapos     0   str2  OK
=inselemapos     0   str3  OK
=inselemapos     0   str4  OK
=obtervalorelem  0   str4  pNaoNULL

== Deturpar ponteiro para cabeca como lixo
=deturpar        0  PtCabecaLixo
=verificarlista  0  ErroEstrutura     
=AceitaFalhasAcumuladas 1

== Destruir a lista
=destruirlista   0
=obternumeroespacosalocados   1 //remanescente de testes anteriores

== Criar Lista
=criarlista      1
=inselemantes    1   str0  OK
=inselemapos     1   str1  OK
=inselemapos     1   str2  OK

== Verificar lista
=verificarlista  1   OK 

== Deturpar tipo cabeca
=deturpar        1   TipoCabeca
=verificarlista  1   ErroEstrutura
=AceitaFalhasAcumuladas  1

== Destruir a lista
=destruirlista   1

== Criar lista
=criarlista      1
=inselemantes    1   str0  OK
=inselemapos     1   str1  OK
=inselemapos     1   str2  OK

== Anular ponteiro para origem
=deturpar        1   OrigemNula
=verificarlista  1   ErroEstrutura
=AceitaFalhasAcumuladas 1

== Anular ponteiro para corrente, origem ja' esta' anulada
=deturpar        1   CorrenteNulo
=verificarlista  1   ErroEstrutura

== Destruir a lista
=destruirlista   1
=obternumeroespacosalocados   4

== Criar lista
=criarlista      3
=inselemantes    3   str0  OK
=inselemapos     3   str1  OK
=inselemapos     3   str2  OK
=avancarelem     3   -1    OK  //Posiciona corrente no elemento do meio

== Desencadear elemento corrente
=deturpar        3   DesencadeiaElem
=verificarlista  3   OK

== Destruir a lista
=destruirlista   3
=obternumeroespacosalocados   5

== Criar Lista
=criarlista      0
=inselemantes    0   str0  OK
=inselemapos     0   str1  OK
=inselemapos     0   str2  OK
=obtervalorelem  0   str2  pNaoNULL

== Anular ponteiro para fim
=deturpar        0   FimNulo
=verificarlista  0   ErroEstrutura
=AceitaFalhasAcumuladas 1

== Destruir a lista
=destruirlista   0
=obternumeroespacosalocados   5

// Os casos de teste a seguir não destroem as listas porque deturpam ponteiros, de modo que ao tentar desalocar um espaço apontado por esse ponteiro
// o teste "voa"

== Criar lista
=criarlista      0
=inselemantes    0   str0  OK
=inselemapos     0   str1  OK
=inselemapos     0   str2  OK

== Anular ponteiro para corrente eliminar
=deturpar        0   EliminaElemCorr	//Corrente é o ultimo elemento da lista
=verificarlista  0   ErroEstrutura
=AceitaFalhasAcumuladas 1		
=obternumeroespacosalocados   11 //Nao pode destruir, mais 6 elems alocados (valores, elems e cabeca)

== Criar Lista
=criarlista      1
=inselemantes    1   str0  OK
=inselemapos     1   str1  OK
=inselemapos     1   str2  OK
=inselemapos     1   str3  OK
=obtervalorelem  1   str3  pNaoNULL

== Deturpar ponteiro para anterior como lixo
=deturpar        1  PtAntLixo
=verificarlista  1  ErroEstrutura       
=AceitaFalhasAcumuladas 1
=obternumeroespacosalocados   20 //Nao pode destruir, mais 9 elems alocados (valores, elems e cabeca)

== Criar Lista
=criarlista      2
=inselemantes    2   str0  OK
=inselemapos     2   str1  OK
=inselemapos     2   str2  OK
=obtervalorelem  2   str2  pNaoNULL
=avancarelem     2   -1    OK  //Posiciona corrente no elemento do meio

== Deturpar ponteiro para proximo como lixo
=deturpar        2  PtProxLixo
=verificarlista  2  ErroEstrutura
=AceitaFalhasAcumuladas 1
=obternumeroespacosalocados   27 //Nao pode destruir, mais 7 elems alocados (valores, elems e cabeca)

== Criar lista
=criarlista      3
=inselemantes    3   str0  OK
=inselemapos     3   str1  OK
=inselemapos     3   str2  OK
=obtervalorelem  3   str2  pNaoNULL
=avancarelem     3   -1    OK  //Posiciona corrente no elemento do meio

== Deturpar ponteiro para corrente como lixo
=deturpar        3   CorrenteLixo
=verificarlista  3   ErroEstrutura	
=AceitaFalhasAcumuladas 1
=obternumeroespacosalocados   34 //Nao pode destruir, mais 7 elems alocados (valores, elems e cabeca)

== Criar lista
=criarlista      4
=inselemantes    4   str0  OK
=inselemapos     4   str1  OK
=inselemapos     4   str2  OK

== Deturpar ponteiro para origem como lixo
=deturpar        4   OrigemLixo
=verificarlista  4   ErroEstrutura
=AceitaFalhasAcumuladas 1
=obternumeroespacosalocados   41 //Nao pode destruir, mais 7 elems alocados (valores, elems e cabeca)

== Criar lista
=criarlista      5
=inselemantes    5   str0  OK
=inselemapos     5   str1  OK
=inselemapos     5   str2  OK

== Deturpar ponteiro para fim como lixo
=deturpar        5   FimLixo
=verificarlista  5   ErroEstrutura
=AceitaFalhasAcumuladas 1
=obternumeroespacosalocados   48 //Nao pode destruir, mais 7 elems alocados (valores, elems e cabeca)
