// Script:    TesteContador-Arv.script
// Autor:     Carla Galdino, Eliana Goldner e Ryniere Silva
// Data:      05/jul/2009
// Propósito: Ilustrar arquivo de script para controle de cobertura
//

== Inicializar valores
=declararparm   lista0  int 0
=declararparm   lista1  int 1
=declararparm   lista2  int 2
=declararparm	lista3  int 3
=declararparm	lista4	int 4
=declararparm	lista5	int 5
=declararparm	lista6	int 6
=declararparm	lista7	int 7
=declararparm	lista8	int 8
=declararparm	lista_nula	int -10

=declararparm   str0    string  "abcdefg"
=declararparm   str1    string  "qwerty"
=declararparm   str2    string  "xxx"
=declararparm   str3    string  "xpto"
=declararparm	strNula	string	"NULA"

=declararparm   OK             int  0
=declararparm   ListaVazia     int  1
=declararparm   FimLista       int  2
=declararparm   NaoAchou       int  3
=declararparm	ErroEstrutura  int  4
=declararparm   FaltouMemoria  int  5
=declararparm   CondRetErro    int  6


//Modos de deturpacao 

=declararparm 	TipoCabeca 	int 1
=declararparm 	OrigemNula	int 2
=declararparm 	FimNulo		int 3
=declararparm 	CorrenteNulo	int 4
=declararparm 	OrigemLixo	int 5
=declararparm 	FimLixo	 	int 6
=declararparm 	CorrenteLixo	int 7
=declararparm 	TipoElem 	int 8
=declararparm 	PtCabecaNulo	int 9
=declararparm 	PtAntNulo	int 10
=declararparm 	PtProxNulo 	int 11
=declararparm 	PtCabecaLixo	int 12
=declararparm 	PtAntLixo	int 13
=declararparm 	PtProxLixo	int 14
=declararparm 	Valor		int 15
=declararparm 	EspacoCabeca 	int 16
=declararparm 	EspacoElem	int 17
=declararparm 	EliminaElemCorr int 18
=declararparm 	DesencadeiaElem	int 19

=declararparm   pNULL          int  0
=declararparm   pNaoNULL       int  1

== Iniciar contagem
=inicializarcontadores  "..\\Produto\\TotalizacaoTesteContadores"
=lercontadores          "..\\Scripts\\DeclaracaodecontadoresLista"
=zerartodoscontadores
=iniciarcontagem

== Verificar Criar a lista 0
=criarlista      lista0

== Verificar Criar a lista 0
=criarlista      lista1

== Verificar assertivas de entrada de avancarElem
=avancarelem      lista0  1  ListaVazia

== Verificar comando recuperar
=avancarelem      lista0   1     OK
=recuperar 

== Verificar contadores, 2 deles já contaram 
=contagemcontador	"LIS_AvancarElementoCorrente" 2
=contagemcontador   "LIS_AvancarElementoCorrente: Avancar elemento em lista vazia."  2

== Verificar Destruir lista
=destruirlista		lista0

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_DestruirLista"  1
=contagemcontador   "LIS_EsvaziarLista"  1

== Verificar inserirElementoAntes: Encadeamento de elemento em lista vazia.
=inselemantes lista1	str1	OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_InserirElementoAntes"  1
=contagemcontador   "LIS_InserirElementoAntes: Encadeamento de elemento em lista vazia."  1
=contagemcontador	"LIS_VerificarEstruturaLista" 1

== Verificar inserirElementoAntes: Encadeamento de elemento quando o elemento corrente é primeiro.
=inselemantes lista1	str2	OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_InserirElementoAntes"  2
=contagemcontador   "LIS_InserirElementoAntes: Encadeamento de elemento em lista que contém elemento(s)."  1
=contagemcontador   "LIS_InserirElementoAntes: Encadeamento de elemento quando o elemento corrente é primeiro."  1
=contagemcontador	"LIS_VerificarEstruturaLista" 2

== Verificar inserirElementoAntes: Encadeamento de elemento quando o elemento corrente não é o primeiro.
=avancarelem      lista1   1     OK
=inselemantes 	lista1	str3	OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador	"LIS_AvancarElementoCorrente: Avancar elemento para frente e nao chegar ao fim." 1
=contagemcontador   "LIS_InserirElementoAntes"  3
=contagemcontador   "LIS_InserirElementoAntes: Encadeamento de elemento em lista que contém elemento(s)."  2
=contagemcontador   "LIS_InserirElementoAntes: Encadeamento de elemento quando o elemento corrente não é o primeiro."  1
=contagemcontador	"LIS_VerificarEstruturaLista" 3

== Verificar inserirElementoApos: Encadeamento de elemento em lista vazia.
=criarlista      lista2
=inselemapos	lista2		str1	OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador	"LIS_InserirElementoApos" 1
=contagemcontador   "LIS_InserirElementoApos: Encadeamento de elemento em lista vazia."  1

== Verificar inserirElementoApos: LIS_InserirElementoApos: Encadeamento de elemento quando o elemento corrente é o último
=inselemapos	lista2		str1	OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador	"LIS_InserirElementoApos" 2
=contagemcontador   "LIS_InserirElementoApos: Encadeamento de elemento em lista que contém elemento(s)." 1
=contagemcontador   "LIS_InserirElementoApos: Encadeamento de elemento quando o elemento corrente é o último."  1

== Verificar inserirElementoApos: Encadeamento de elemento quando o elemento corrente não é o último.
=avancarelem      lista2   -1     OK
=inselemapos	lista2		str2	OK

== Verificar novo(s) contadores de passagem não nulos 43
=contagemcontador   "LIS_InserirElementoApos: Encadeamento de elemento em lista que contém elemento(s)." 2
=contagemcontador   "LIS_InserirElementoApos: Encadeamento de elemento quando o elemento corrente não é o último."  1
=contagemcontador	"LIS_AvancarElementoCorrente: Avancar elemento para trás e nao chegar ao inicio." 1

== Verificar IrInicioLista
=irinicio lista2

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_IrInicioLista" 1

== Verificar Excluir Elemento: Excluir elemento em lista vazia.
=criarlista		lista3
=excluirelem	lista3   ListaVazia

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_ExcluirElemento" 1
=contagemcontador	"LIS_ExcluirElemento: Excluir elemento em lista vazia." 1

== Verificar Excluir Elemento: Excluir origem lista.
=inselemapos	lista3		str3	OK
=excluirelem	lista3   OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_ExcluirElemento: Excluir origem lista." 1
=contagemcontador	"LIS_ExcluirElemento: Excluir fim lista." 1

== Verificar Excluir Elemento: Excluir elemento que nao é origem da lista.
=destruirlista		lista3
=criarlista			lista3
=inselemantes 		lista3		str3		OK
=inselemantes 		lista3		str2		OK
=inselemantes 		lista3		str1		OK
=inselemantes 		lista3		str0		OK
=avancarelem		lista3		2			OK	
=excluirelem		lista3   	OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_ExcluirElemento: Excluir elemento que nao é origem lista." 1
=contagemcontador	"LIS_ExcluirElemento: Excluir elemento que nao é fim lista." 1

== Verificar Avancar Elemento: Avancar elemento para frente e chegar ao fim da lista
=avancarelem		lista3		2		FimLista

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_AvancarElementoCorrente: Avancar elemento para frente e chegar ao fim da lista." 1
=contagemcontador	"LIS_ExcluirElemento: Excluir elemento que nao é fim lista." 1

== Verificar Avancar Elemento: Avancar elemento para tras e chegar ao inicio da lista
=avancarelem		lista3		-5		FimLista

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_AvancarElementoCorrente: Avancar elemento para tras e chegar ao inicio da lista." 1

== Verificar Ir Final Lista
=irfinal		lista3

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_IrFinalLista" 1

== Verificar Avancar Elemento: Nao avancar elemento.
=avancarelem		lista3		0		OK

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_AvancarElementoCorrente: Nao avancar elemento." 1

== Verificar Esvaziar Lista: Retirar elemento não nulo da lista.
=esvaziarlista		lista3

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_EsvaziarLista:Retirar elemento não nulo da lista." 3

== Verificar Deturpação: Parametro pListaParm eh nulo.
=deturpar 	lista_nula	0

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador	"LIS_Deturpar" 1
=contagemcontador   "LIS_Deturpar: Parametro pListaParm eh nulo." 1

== Verificar Deturpação: Modifica o tipo cabeca.
=deturpar	lista1	TipoCabeca

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Modifica o tipo cabeca." 1

== Verificar Deturpação: Anula ponteiro origem.
=deturpar	lista1	OrigemNula

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Anula ponteiro origem." 1

== Verificar Deturpação: Anula ponteiro corrente.
=deturpar	lista1	CorrenteNulo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Anula ponteiro corrente." 1

== Verificar Deturpação: Faz origem apontar para lixo.
=deturpar	lista1	OrigemLixo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Faz origem apontar para lixo." 1


== Verificar Deturpação: Faz corrente apontar para lixo.
=deturpar	lista1	CorrenteLixo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Faz corrente apontar para lixo." 1

== Verificar Deturpação: Deturpar espaço cabeca.
=deturpar	lista1	EspacoCabeca

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Deturpar espaço cabeca." 1

== Verificar Deturpação: Deturpa elemento.
=deturpar	lista1	20

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Deturpa elemento." 1

== Verificar Deturpação: Modifica tipo elemento corrente.
=deturpar	lista1	TipoElem

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Modifica tipo elemento corrente." 1

== Verificar Deturpação: Anula ponteiro cabeça.
=deturpar	lista1	PtCabecaNulo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Anula ponteiro cabeça." 1

== Verificar Deturpação: Anula ponteiro anterior.
=deturpar	lista1	PtAntNulo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Anula ponteiro anterior." 1

== Verificar Deturpação: Anula ponteiro proximo.
=deturpar	lista1	PtProxNulo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Anula ponteiro proximo." 1

== Verificar Deturpação: Faz ponteiro cabeça apontar para lixo.
=deturpar	lista1	PtCabecaLixo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Faz ponteiro cabeça apontar para lixo." 1

== Verificar Deturpação: Faz ponteiro anterior apontar para lixo.
=deturpar	lista1	PtAntLixo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Faz ponteiro anterior apontar para lixo." 1

== Verificar Deturpação: Faz ponteiro proximo apontar para lixo.
=deturpar	lista1	PtProxLixo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Faz ponteiro proximo apontar para lixo." 1

== Verificar Deturpação: Atribui valor fora do domínio do espaço..
=deturpar	lista2	Valor

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Atribui valor fora do domínio do espaço." 1

== Verificar Deturpação: Desencadeia elemento sem libera-lo como free.
=deturpar	lista1	DesencadeiaElem

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Desencadeia elemento sem libera-lo como free." 1

== Verificar Deturpação: Anula ponteiro fim.
=destruirlista		lista2
=criarlista			lista2
=inselemantes		lista2		str3	OK
=inselemantes		lista2		str2	OK
=inselemantes		lista2		str1	OK
=deturpar			lista2		FimNulo

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Anula ponteiro fim." 1

== Verificar Inserir elemento antes: Falta de memória ao criar elemento da lista.
=destruirlista					lista2
=criarlista						lista2
=limitarmemoriadisponivel		190
=inselemantes					lista2		str0		FaltouMemoria

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_InserirElementoAntes: Falta de memória a criar elemento da lista." 1

== Verificar Inserir elemento antes: Falta de memória a criar elemento da lista.
=eliminarlimitesespaco
=limitarmemoriadisponivel		190
=inselemapos					lista2		str0		FaltouMemoria
=eliminarlimitesespaco

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_InserirElementoApos: Falta de memória a criar elemento da lista." 1

== Verificar Obter Valor: Obter valor de elemento corrente nao nulo.
=inselemantes		lista2		str2		OK
=obtervalorelem		lista2		str2		pNaoNULL

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_ObterValor" 1
=contagemcontador   "LIS_ObterValor: Obter valor de elemento corrente nao nulo." 1

== Verificar Obter Valor: Obter valor de elemento corrente nulo.
=criarlista			lista4
=obtervalorelem		lista4			strNula		pNULL

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_ObterValor" 2
=contagemcontador   "LIS_ObterValor: Obter valor de elemento corrente nulo." 1

== Verificar Estrutura Lista: Numero elementos lista != numero elementos encadeados.
=eliminarlimitesespaco
=inselemantes			lista4		str2				OK
=deturpar				lista4		DesencadeiaElem

=verificarestrutura		lista4		CondRetErro

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_VerificarEstruturaLista: Numero elementos lista != numero elementos encadeados." 1

== Verificar Deturpação: Faz ponteiro proximo apontar para lixo.
=criarlista				lista5
=inselemantes			lista5		str0		OK
=inselemantes			lista5		str1		OK
=deturpar				lista5		PtProxLixo
=verificarestrutura		lista5		CondRetErro

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_VerificarEstruturaLista: Encadeamento incorreto na lista." 1

== Verificar Deturpação: Deturpar espaço elemento.
=criarlista				lista6
=inselemantes			lista6		str0		OK
=inselemantes			lista6		str1		OK
=deturpar				lista6		EspacoElem

== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Deturpar espaço elemento." 1

== Verificar Deturpação: Elimina elemento corrente.
=criarlista				lista7
=inselemantes			lista7		str0		OK
=inselemantes			lista7		str1		OK
=deturpar				lista7		EliminaElemCorr


== Verificar novo(s) contadores de passagem não nulos
=contagemcontador   "LIS_Deturpar: Elimina elemento corrente." 1

== Verificar Deturpação: Faz fim apontar para lixo.
=criarlista lista8
=inselemantes lista8 str0 OK
=inselemantes lista8 str1 OK
=deturpar lista8 FimLixo

== Verificar novo(s) contadores de passagem não nulos
=verificarcontagens 0
=contagemcontador "LIS_Deturpar: Faz fim apontar para lixo." 1
=AceitaFalhasAcumuladas 0

=terminarcontadores  OK

// fim
